FROM mysql:8

# RUN apt-get update \
#     && apt-get install wget -y \
#     && apt-get install postgresql-14-postgis-3 -y \
#     && apt-get install postgis -y

# Variables needed at runtime to configure postgres and run the initdb scripts
ENV MYSQL_DATABASE 'bug_app'
ENV MYSQL_USER 'bug_app_user'
ENV MYSQL_PASSWORD 'secret'
ENV MYSQL_ROOT_PASSWORD 'secret'

# Copy in the load-extensions script
# COPY ./docker/db/load-extensions.sh /docker-entrypoint-initdb.d/