FROM postgres:14

RUN apt-get update \
    && apt-get install wget -y \
    && apt-get install postgresql-14-postgis-3 -y \
    && apt-get install postgis -y

# Variables needed at runtime to configure postgres and run the initdb scripts
ENV POSTGRES_DB 'my_app_local'
ENV POSTGRES_USER 'my_app_local'
ENV POSTGRES_PASSWORD 'secret_local'


# Copy in the load-extensions script
COPY ./docker/db/load-extensions.sh /docker-entrypoint-initdb.d/