FROM mysql:8

# RUN apt-get update \
#     && apt-get install wget -y \
#     && apt-get install postgresql-14-postgis-3 -y \
#     && apt-get install postgis -y

# Variables needed at runtime to configure postgres and run the initdb scripts
ENV MYSQL_DATABASE 'my_app_local'
ENV MYSQL_USER 'my_app_local'
ENV MYSQL_PASSWORD 'secret_local'

# Copy in the load-extensions script
COPY ./docker/db/load-extensions.sh /docker-entrypoint-initdb.d/